server:
  port: 9008
  
spring:  application:    name: CONFIG-SERVER
  
  cloud:    config:      server:        git:          uri: https://github.com/devOak28/microservices-hotel-rating-config
          clone-on-start: true
    
